apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-docker-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-docker
  template:
    metadata:
      labels:
        app: java-docker
    spec:
      containers:
      - name: java-docker
        image: "gcr.io/jenkins-gcr:java-docker"
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
